# -*- mode: python -*-

import os
from penchy.jobs import *

node = NodeSetting('localhost', 22, os.environ['USER'], '/tmp', '/usr/bin')

jvm = jvms.CacheGrindJVM('java')
composition = SystemComposition(jvm, node, name="valgrindwrapped")

w = workloads.ScalaBench('dummy')
jvm.workload = w

f = filters.Print()
dump = filters.Dump()
composition.flow = [jvm >> dump >> f]

job = Job(compositions=composition,
          server_flow=[],
          invocations = 1
          )
