# -*- mode: python -*-

import os
from penchy.jobs import *

node = NodeSetting('localhost', 22, os.environ['USER'], '/tmp', '/usr/bin')

jvm = jvms.JVM('java')
composition = SystemComposition(jvm, node)

w = workloads.ScalaBench('fop')
t = tools.HProf('cpu=times')
jvm.workload = w
jvm.tool = t

f = filters.HProfCpuTimes()

composition.flow = [t >> f >> filters.Print()]

job = Job(compositions=composition,
          server_flow=[],
          invocations = 1
          )
