#! /bin/sh

PYTHONVER=2.6

pep8 --exclude=".git,.ropeproject,*pyc,*pyo" \
    --filename="*.py" \
    --ignore="E201,E202,E203" penchy

pep8ret=$?

pychecker penchy
pycheckerret=$?

# pyflakes penchy
# pyflakesret=$?
pyflakesret=0

unit2 discover -s penchy/tests -t .
unittests=$?


ret=$(python -c 'import sys; print sum(map(int, sys.argv[3:]))' \
    $pep8ret $pycheckerret $pyflakesret)

exit $ret
