#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from subprocess import call as scall

def call(cmd):
    try:
        return scall(cmd)
    except OSError as e:
        print e
        print "Try installing {0}".format(cmd[0])
        return 1


def main(additional=None, human=False):
    os.environ['PYTHONVER'] = '2.6'
    cmds = [['pep8',
             '--exclude', '.git,.ropeproject,*pyc,*pyo',
             '--filename=*.py',
             '--ignore=E201,E202,E203,E501',
             '--repeat',
             '--count']
            + (['--show-source', '--show-pep8', 'penchy'] if human
               else ['penchy']),
            ['pychecker', 'penchy'],
            ['unit2', 'discover', '-s', 'penchy/tests', '-t', '.']
           ]
    cmds += additional if additional is not None else []
    return sum(call(cmd) for cmd in cmds)


def run_all():
    """
    Run all checks, for manual purpose, not for git hook
    """
    main(additional=[['pyflakes', 'penchy'],
                     ['pylint', 'penchy']],
         human=True)


if __name__ == '__main__':
    import sys
    if '--all' in sys.argv:
        run_all()
    else:
        sys.exit(main(human='--human' in sys.argv))
